
import {
  Calendar,
  FileSpreadsheet,
  Mail,
  Database,
  BarChart3,
  Globe,
  Briefcase,
} from "lucide-react"

export const assistentes = [
  {
    id: 1,
    userId: "user-1-id",
    slug: "ana-carolina-silva",
    nome: "Ana Carolina Silva",
    titulo: "Especialista em Gestão Médica",
    foto: "/placeholder.svg?height=80&width=80",
    localizacao: "São Paulo, SP",
    disponibilidade: "Disponível",
    avaliacaoMedia: 4.9,
    clientesAtendidos: 47,
    horasTrabalho: 1240,
    especialidades: ["Gestão de Agenda", "Faturamento Médico", "Atendimento ao Paciente"],
    verificada: true,
    tempoResposta: "2h",
    apresentacao:
      "Especialista em gestão médica com 5+ anos de experiência. Transformo consultórios em operações eficientes e organizadas.",
    servicos: [
      "Gestão de agenda médica",
      "Faturamento e cobrança",
      "Atendimento ao paciente",
      "Relatórios gerenciais",
      "Controle de estoque médico",
    ],
    ferramentas: [
      { nome: "Google Agenda", icone: Calendar },
      { nome: "Excel", icone: FileSpreadsheet },
      { nome: "Gmail", icone: Mail },
      { nome: "Sistema Médico", icone: Database },
    ],
    depoimentos: [
      { cliente: "Dr. Carlos Mendes", texto: "Ana revolucionou meu consultório. Organização impecável!" },
      { cliente: "Dra. Maria Santos", texto: "Profissional excepcional, recomendo sem hesitar." },
    ],
    certificacoes: ["Gestão em Saúde - FGV", "Atendimento ao Cliente - Sebrae", "Excel Avançado - Microsoft"],
  },
  {
    id: 2,
    userId: "user-2-id",
    slug: "mariana-santos",
    nome: "Mariana Santos",
    titulo: "E-commerce & Marketing Digital",
    foto: "/placeholder.svg?height=80&width=80",
    localizacao: "Rio de Janeiro, RJ",
    disponibilidade: "Vagas Limitadas",
    avaliacaoMedia: 4.8,
    clientesAtendidos: 32,
    horasTrabalho: 980,
    especialidades: ["Marketing Digital", "Redes Sociais", "E-commerce"],
    verificada: true,
    tempoResposta: "1h",
    apresentacao:
      "Especialista em e-commerce e marketing digital. Ajudo empresas a crescerem online com estratégias eficazes.",
    servicos: [
      "Gestão de redes sociais",
      "Criação de campanhas publicitárias",
      "Otimização de e-commerce",
      "Análise de métricas",
      "Criação de conteúdo",
    ],
    ferramentas: [
      { nome: "Google Analytics", icone: BarChart3 },
      { nome: "Facebook Ads", icone: Globe },
      { nome: "Planilhas", icone: FileSpreadsheet },
      { nome: "Canva", icone: Briefcase },
    ],
    depoimentos: [
      { cliente: "João Silva", texto: "Mariana aumentou nossas vendas em 150% em 6 meses!" },
      { cliente: "Loja Fashion", texto: "Profissional incrível, resultados surpreendentes." },
    ],
    certificacoes: ["Google Ads Certified", "Facebook Blueprint", "E-commerce Specialist"],
  },
  {
    id: 3,
    userId: "user-3-id",
    slug: "juliana-oliveira",
    nome: "Juliana Oliveira",
    titulo: "Gestão Administrativa & Financeira",
    foto: "/placeholder.svg?height=80&width=80",
    localizacao: "Belo Horizonte, MG",
    disponibilidade: "Disponível",
    avaliacaoMedia: 5.0,
    clientesAtendidos: 28,
    horasTrabalho: 850,
    especialidades: ["Gestão Financeira", "Controle de Estoque", "Relatórios"],
    verificada: true,
    tempoResposta: "3h",
    apresentacao:
      "Experienciada em gestão administrativa e financeira. Auxilio na otimização de processos e aumento de produtividade.",
    servicos: [
      "Gestão financeira",
      "Controle de estoque",
      "Relatórios gerenciais",
      "Planejamento estratégico",
      "Análise de dados",
    ],
    ferramentas: [
      { nome: "Excel", icone: FileSpreadsheet },
      { nome: "Google Sheets", icone: Database },
      { nome: "Outlook", icone: Mail },
      { nome: "ERP", icone: Briefcase },
    ],
    depoimentos: [
      {
        cliente: "Empresa XYZ",
        texto: "Juliana é uma verdadeira especialista. Nosso fluxo financeiro ficou muito mais eficiente!",
      },
      { cliente: "Departamento Financeiro", texto: "Profissional confiável e dedicada." },
    ],
    certificacoes: [
      "Certificado em Gestão Financeira - IFMG",
      "Contabilidade Digital - Sebrae",
      "Excel Profissional - Microsoft",
    ],
  },
  {
    id: 4,
    userId: "user-4-id",
    slug: "camila-rodriguez",
    nome: "Camila Rodriguez",
    titulo: "Assistente Jurídica & Compliance",
    foto: "/placeholder.svg?height=80&width=80",
    localizacao: "Curitiba, PR",
    disponibilidade: "Disponível",
    avaliacaoMedia: 4.9,
    clientesAtendidos: 19,
    horasTrabalho: 720,
    especialidades: ["Processos Jurídicos", "Compliance", "Documentação"],
    verificada: true,
    tempoResposta: "4h",
    apresentacao:
      "Assistente jurídica especializada em processos legais. Garanto segurança e conformidade para seus negócios.",
    servicos: ["Assistência jurídica", "Compliance", "Documentação", "Análise de riscos", "Regulamentações"],
    ferramentas: [
      { nome: "Word", icone: FileSpreadsheet },
      { nome: "Outlook", icone: Mail },
      { nome: "Sistema Jurídico", icone: Database },
      { nome: "Google Docs", icone: Briefcase },
    ],
    depoimentos: [
      { cliente: "Advogado João", texto: "Camila é uma mão na roda. Nosso compliance ficou muito mais robusto!" },
      { cliente: "Departamento Jurídico", texto: "Profissional altamente competente e confiável." },
    ],
    certificacoes: ["Advogado - UFPR", "Compliance em Negócios - FGV", "Direito Empresarial - UNICAMP"],
  },
  {
    id: 5,
    userId: "user-5-id",
    slug: "fernanda-costa",
    nome: "Fernanda Costa",
    titulo: "Recursos Humanos & Recrutamento",
    foto: "/placeholder.svg?height=80&width=80",
    localizacao: "Porto Alegre, RS",
    disponibilidade: "Vagas Limitadas",
    avaliacaoMedia: 4.7,
    clientesAtendidos: 35,
    horasTrabalho: 1100,
    especialidades: ["Recrutamento", "Gestão de Pessoas", "Treinamentos"],
    verificada: true,
    tempoResposta: "2h",
    apresentacao: "Especializada em recursos humanos e recrutamento. Auxilio na contratação e gestão de talentos.",
    servicos: ["Recrutamento", "Gestão de pessoas", "Treinamentos", "Análise de desempenho", "Planejamento de RH"],
    ferramentas: [
      { nome: "LinkedIn", icone: Globe },
      { nome: "Excel", icone: FileSpreadsheet },
      { nome: "Google Forms", icone: Briefcase },
      { nome: "Sistema RH", icone: Database },
    ],
    depoimentos: [
      {
        cliente: "HR Manager",
        texto: "Fernanda é incrível. Nosso processo de recrutamento ficou muito mais eficiente!",
      },
      { cliente: "Departamento de RH", texto: "Profissional dedicada e altamente competente." },
    ],
    certificacoes: ["Certificado em RH - UFRGS", "Recrutamento e Seleção - Sebrae", "Excel Avançado - Microsoft"],
  },
  {
    id: 6,
    userId: "user-6-id",
    slug: "beatriz-almeida",
    nome: "Beatriz Almeida",
    titulo: "Consultórios Odontológicos",
    foto: "/placeholder.svg?height=80&width=80",
    localizacao: "Brasília, DF",
    disponibilidade: "Disponível",
    avaliacaoMedia: 4.8,
    clientesAtendidos: 23,
    horasTrabalho: 690,
    especialidades: ["Agendamento", "Gestão de Tratamentos", "Pacientes"],
    verificada: true,
    tempoResposta: "1h",
    apresentacao:
      "Assistente especializada em consultórios odontológicos. Auxilio na gestão eficiente e organizada de clínicas.",
    servicos: [
      "Agendamento odontológico",
      "Gestão de tratamentos",
      "Atendimento ao paciente",
      "Relatórios",
      "Controle de estoque odontológico",
    ],
    ferramentas: [
      { nome: "Google Agenda", icone: Calendar },
      { nome: "Excel", icone: FileSpreadsheet },
      { nome: "Gmail", icone: Mail },
      { nome: "Sistema Odontológico", icone: Database },
    ],
    depoimentos: [
      {
        cliente: "Dentista Carlos",
        texto: "Beatriz é uma profissional excelente. Nosso consultório ficou muito mais organizado!",
      },
      { cliente: "Clínica Odontológica", texto: "Profissional confiável e dedicada." },
    ],
    certificacoes: [
      "Gestão em Odontologia - UNB",
      "Atendimento ao Paciente - Sebrae",
      "Excel Profissional - Microsoft",
    ],
  },
]
