export const SUPABASE_URL = 'https://kjmpdlmehwjlckhqfgra.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqbXBkbG1laHdqbGNraHFmZ3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTA3NzcsImV4cCI6MjA2OTYyNjc3N30.HNAtXLvi2fSeJ7CRnMqdX7cAU8fxzgEJRz07eS3yRYA';
