export type Cliente = {
  id: string;
  user_id: string;
  client_id: string;
  avatar_url: string | null;
  person_type: 'cpf' | 'cnpj' | null;
  company_name: string | null;
  cnpj: string | null;
  representative_name: string | null;
  representative_rg: string | null;
  representative_cpf: string | null;
  full_name: string | null;
  nationality: string | null;
  civil_status: string | null;
  profession: string | null;
  rg: string | null;
  cpf: string | null;
  address: string | null;
  created_at: string;
  updated_at: string;
};

export type Proposta = {
  id: string;
  user_id: string;
  name: string;
  services: string[];
  created_at: string;
  updated_at: string;
  payment_type?: 'fixed' | 'hourly' | 'project';
  value?: number;
  value_in_words?: string;
  payment_day?: number;
  payment_method?: string;
  contract_duration_type?: 'indefinite' | 'definite';
  contract_duration_months?: number;
  start_date?: string;
  end_date?: string;
  jurisdiction_city?: string;
  jurisdiction_state?: string;
};
