
# Supabase Project Config
# Reference: https://supabase.com/docs/reference/cli/config

# [db]
# local_port = 5432
# major_version = 15

# [studio]
# local_port = 54321

# [api]
# local_port = 54322
# health_check.enabled = true

[functions]
  [functions.send-billing-reminders]
    schedule = "0 0 * * *" # Roda todos os dias à meia-noite (UTC)
